# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----uploadvideos

------uploadvideos
Content-Disposition: form-data; name="image"; filename="audioexample.mp3"
Content-Type: audio/mpeg

< ./audioexample.mp3
------uploadvideos--

###

# @name create-transcription
POST http://localhost:3333/videos/e5c5a45b-ad18-47a6-b36c-1a33f1639969/transcription
Content-Type: application/json

{
  "prompt": "modal, dialog, javascript"
}


###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "e5c5a45b-ad18-47a6-b36c-1a33f1639969",
  "temperature": 0.5,
  "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}